import type { Metadata } from "next";
import "./globals.css";
import { Odibee_Sans } from "next/font/google";
const odibeeSans = Odibee_Sans({
  variable: "--font-odibee-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${odibeeSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
